### ISSUE TITLE
Fs2004 pyuipc.FSUIPCException: FSUIPC error: 13 (IPC request contains bad data)

### ISSUE THREAD

**Issue by Gupyzer0** [tjensen/fsuipc#4]
While trying the example in the readme file i got:
**pyuipc.FSUIPCException: FSUIPC error: 13 (IPC request contains bad data)**

**Environment (please complete the following information):**
 - Windows edition: Windows 10 Pro
 - Windows version: 1909
 - Windows build: 18363.418
 - Python: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
 - Simulator version : fs 9.1
 - FSUIPC version: 3.999z8

**Comment by tjensen** [comment]
Hi @Gupyzer0. Thanks for your bug report.

I presume that "fs 9.1" refers to Microsoft Flight Simulator 2004 with the v9.1 update. Unfortunately, I do not have this software, so I am unable to reproduce the issue.

One thing I noticed is that you are using a 64-bit version of Python. Since FS2004 is 32-bit software, you might need to use a 32-bit version of Python in order to interface with the simulator using FSUIPC.

Can you try installing a 32-bit version of Python (e.g. https://www.python.org/ftp/python/3.9.2/python-3.9.2.exe) and retry running the example? Please report back whether this resolved the issue.

Thanks,
Tim

**Comment by Gupyzer0** [comment]
Success !

At first i downloaded the 32bit python as you said and tried, i got this error message.

**pyuipc.FSUIPCException: FSUIPC error: 12 (IPC sendmessage failed all retries)**

Which is different from what i was receiving before, so next i ran the console with admin privileges and it is working now! . I'm not running fs9 as an admin but guess i **needed to execute the script as an admin.** Of course i tried that before so yeah **you were 100% right that i needed python 32bit** which makes sense with fs9 being 32 too.

Thank you very much !.

**Comment by tjensen** [comment]
@Gupyzer0 I'm glad you were able to get it working! I'm going to leave this issue open as a reminder to myself to update the documentation about needing to run as an administrator.

**Comment by Gupyzer0** [comment]
> @Gupyzer0 I'm glad you were able to get it working! I'm going to leave this issue open as a reminder to myself to update the documentation about needing to run as an administrator.

Ok !, once again, thanks for your assistance.
